### ISSUE TITLE
Plugin v0.3.1 crashes with my UDL

### ISSUE THREAD

**Issue by ianthetechie** [Lonami/uniffi-dl#6]
Hey Lonami,

First, thanks for taking the time to make this plugin! I'm trying it out for one of my (very early stage) projects, Ferrostar.

Unfortunately it crashes upon loading the UDL file. I've included the IntelliJ (well, CLion) stack trace and the UDL file that reproduces the issue:

Stack trace:

```
java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiElement.getNode()" because the return value of "com.intellij.psi.PsiElement.getFirstChild()" is null
	at dev.lonami.uniffidl.psi.impl.UdlPsiImplUtil.getNameIdentifier(UdlPsiImplUtil.java:128)
	at dev.lonami.uniffidl.psi.impl.UdlRegularOperationImpl.getNameIdentifier(UdlRegularOperationImpl.java:44)
	at com.intellij.model.psi.impl.PsiElement2Declaration.getIdentifyingElement(PsiElement2Declaration.java:119)
	at com.intellij.model.psi.impl.PsiElement2Declaration.getIdentifyingElement(PsiElement2Declaration.java:112)
	at com.intellij.model.psi.impl.PsiElement2Declaration.getDeclarationRangeFromPsi(PsiElement2Declaration.java:73)
	at com.intellij.model.psi.impl.PsiElement2Declaration.createFromDeclaredPsiElement(PsiElement2Declaration.java:68)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:126)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:42)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:24)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:202)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:194)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$submitIdentifierHighlighterPass$5(BackgroundHighlighter.java:203)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

UDL:

```
//
// Namespace to encapsulate top-level functions
//

namespace ferrostar {
    RouteRequestGenerator create_valhalla_request_generator(string endpoint_url, string profile);
    RouteResponseParser create_osrm_response_parser(u32 polyline_precision);
};

//
// Error types
//

[Error]
enum RoutingRequestGenerationError {
    "NotEnoughWaypoints",
    "JsonError",
    "UnknownError"
};

[Error]
interface RoutingResponseParseError {
    ParseError(string error);
    UnknownError();
};

//
// Data structures
//

dictionary GeographicCoordinates {
    double lat;
    double lng;
};

dictionary Course {
    double degrees;
    double accuracy;
};

dictionary UserLocation {
    GeographicCoordinates coordinates;
    double horizontal_accuracy;
    Course? course;
};

dictionary Route {
    sequence<GeographicCoordinates> geometry;
    sequence<GeographicCoordinates> waypoints;
};

[Enum]
interface RouteRequest {
    HttpPost(string url, record<DOMString, string> headers, sequence<u8> body);
};

//
// Callback interfaces (foreign code can implement these to extend functionality)
//

callback interface RouteRequestGenerator {
    [Throws=RoutingRequestGenerationError]
    RouteRequest generate_request(sequence<GeographicCoordinates> waypoints);
};

callback interface RouteResponseParser {
    [Throws=RoutingResponseParseError]
    sequence<Route> parse_response(sequence<u8> response);
};

interface RouteAdapter {
    constructor(RouteRequestGenerator request_generator, RouteResponseParser response_parser);
    [Name=new_valhalla_http]
    constructor(string endpoint_url, string profile);

    [Throws=RoutingRequestGenerationError]
    RouteRequest generate_request(sequence<GeographicCoordinates> waypoints);

    [Throws=RoutingResponseParseError]
    sequence<Route> parse_response(sequence<u8> response);
};

interface NavigationController {
    constructor(UserLocation last_user_location, Route route);

    void update_user_location(UserLocation location);
    // TODO: Expose read-only model
};
```

**Comment by Lonami** [comment]
It seems like:

```udl
interface RoutingResponseParseError {
    ParseError(string error);
};
```

is enough to cause the error.

**Comment by Lonami** [comment]
Hopefully I didn't mess up this time:
![image](https://github.com/Lonami/uniffi-dl/assets/6297805/a65ea38d-faa4-4a64-9268-b68e7f1a25f6)

**Comment by ianthetechie** [comment]
:D
